/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiamondsRouteImport } from './routes/diamonds'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LudoRouteImport } from './routes/ludo'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as StatsRouteImport } from './routes/stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiamondsRoute = DiamondsRouteImport.update({
  id: '/diamonds',
  path: '/diamonds',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LudoRoute = LudoRouteImport.update({
  id: '/ludo',
  path: '/ludo',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diamonds': typeof DiamondsRoute
  '/explore': typeof ExploreRoute
  '/gifts': typeof GiftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ludo': typeof LudoRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/spin': typeof SpinRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diamonds': typeof DiamondsRoute
  '/explore': typeof ExploreRoute
  '/gifts': typeof GiftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ludo': typeof LudoRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/spin': typeof SpinRoute
  '/stats': typeof StatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diamonds': typeof DiamondsRoute
  '/explore': typeof ExploreRoute
  '/gifts': typeof GiftsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/ludo': typeof LudoRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/spin': typeof SpinRoute
  '/stats': typeof StatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/diamonds'
    | '/explore'
    | '/gifts'
    | '/leaderboard'
    | '/ludo'
    | '/messages'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/spin'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/diamonds'
    | '/explore'
    | '/gifts'
    | '/leaderboard'
    | '/ludo'
    | '/messages'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/spin'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/diamonds'
    | '/explore'
    | '/gifts'
    | '/leaderboard'
    | '/ludo'
    | '/messages'
    | '/profile'
    | '/rooms'
    | '/settings'
    | '/spin'
    | '/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DiamondsRoute: typeof DiamondsRoute
  ExploreRoute: typeof ExploreRoute
  GiftsRoute: typeof GiftsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LudoRoute: typeof LudoRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  SpinRoute: typeof SpinRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diamonds': {
      id: '/diamonds'
      path: '/diamonds'
      fullPath: '/diamonds'
      preLoaderRoute: typeof DiamondsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ludo': {
      id: '/ludo'
      path: '/ludo'
      fullPath: '/ludo'
      preLoaderRoute: typeof LudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DiamondsRoute: DiamondsRoute,
  ExploreRoute: ExploreRoute,
  GiftsRoute: GiftsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LudoRoute: LudoRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  SpinRoute: SpinRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
